imports:
    - php

filter:
#    paths:
#        - Source/*
    excluded_paths:
        - Test/*
tools:
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.

    php_sim: false
    php_cpd: false
