language: php
php:
  - 5.6
  - 5.5
#  - 5.4
#  - hhvm

services:
  - mongodb
  - redis-server

before_script:
  - ./Bin/apc-install.sh
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - mysql -e "create database IF NOT EXISTS test;" -uroot

script: ./cli Ice:Phpunit_Run

addons:
  code_climate:
    repo_token: 781407b639c8efcf74cdd6daadb7264131fb309562f73b4235dcccf4b250f6a3

after_script:
- travis_retry wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --access-token="e94d23c2fde554972a6c0e1ca4fee4db3b97663e82b35267c3f85c9f0726d0cc" --format=php-clover Var/vendor/phpunit/coverage.xml
