language: php
php:
  - 5.5
  - 5.4
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --bootstrap bootstrap.php --coverage-text Test
