language: php
php:
  - 5.6
  - 5.5
#  - 5.4
#  - hhvm

services:
  - redis-server
  - mongodb

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - ./Bin/install.sh
  - wget http://getcomposer.org/composer.phar
  - ./cli Ice:Composer_Update

script: ./cli Ice:Phpunit_Run

after_script:
- travis_retry wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --access-token="e94d23c2fde554972a6c0e1ca4fee4db3b97663e82b35267c3f85c9f0726d0cc" --format=php-clover Var/vendor/phpunit/coverage.xml
